# Generated by Django 3.1.4 on 2020-12-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=2)),
                ('time', models.TimeField()),
                ('day', models.DateField()),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
