# Generated by Django 2.2 on 2020-12-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherAppApi', '0002_auto_20201223_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
    ]
