# Generated by Django 3.1.4 on 2020-12-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherAppApi', '0004_auto_20201223_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='day',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
