# Generated by Django 3.1.4 on 2020-12-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherAppApi', '0005_auto_20201226_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='day',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='weather',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
