# Generated by Django 3.1.4 on 2020-12-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherAppApi', '0006_auto_20201227_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='time',
            field=models.TimeField(),
        ),
    ]
